### ISSUE TITLE
Legal info (notices, licenses, etc.) gets lost in 'jar-with-dependencies' build of liberty-langserver-lemminx extension

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-language-server#102]
Because of the approach used to build the **liberty-langserver-lemminx-1.0-SNAPSHOT-jar-with-dependencies.jar**, using the assembly plugin with     `<descriptorRef>jar-with-dependencies</descriptorRef>` config, the contents of the various dependency JARs get smashed together and overwritten.

This makes it harder to consume this JAR downstream, e.g. in the Liberty Tools Eclipse feature, where we have to identify the legal info and bubble it up to the users of our feature.   

E.g. if I build the lemminx-liberty module I see these license/notice files:
```
> 
> META-INF/LICENSE.txt
> META-INF/LICENSE.md
> META-INF/NOTICE.md

```

It is unclear which dependency each of these came from, since they have been smashed together.

I think we should either do a better job at preserving the individual parts or just remove them altogether.   

The latter is the approach we took in the Liberty Tools Eclipse Early Release .  If you look at 
https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/bundles/io.openliberty.tools.eclipse.lsp4e/lib/liberty-langserver-lemminx-1.0-SNAPSHOT-jar-with-dependencies.jar you'll see we removed these and rely on https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/bundles/io.openliberty.tools.eclipse.lsp4e/about.html to track the info.

That could work.  Or if you want to look at preserving them, renaming them or adding to a different per-dependency dir, that could work too.

**Comment by cherylking** [comment]
@scottkurz I'm thinking it is better to preserve the license info if possible, since we do not know how the other IDEs will surface the license info yet. I think the `ApacheLicenseResourceTransformer` and `ApacheNoticeResourceTransformer` described [here](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html) should work to preserve the third-party licenses and merge the notices. What do you think?

**Comment by scottkurz** [comment]
> @scottkurz I'm thinking it is better to preserve the license info if possible, since we do not know how the other IDEs will surface the license info yet. I think the `ApacheLicenseResourceTransformer` and `ApacheNoticeResourceTransformer` described [here](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html) should work to preserve the third-party licenses and merge the notices. What do you think?

Never tried them myself but that seems like this exact use case so probably worth a try.  Good find!
