### ISSUE TITLE
Diagnostic doesn't work properly with whitespace around the `=` sign

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/liberty-language-server#141]
Diagnostic does not work with whitespace before `=`
![image](https://user-images.githubusercontent.com/689163/205715751-67923075-4286-418f-ba88-deb11f02c376.png)

Diagnostic includes whitespaces in the value when there is whitespace after `=`
![image](https://user-images.githubusercontent.com/689163/205715644-3b16dc88-9f2c-4c37-b753-381228550c75.png)

Diagnostic works correctly when there is no whitespace around the `=` sign
![image](https://user-images.githubusercontent.com/689163/205715688-2f5e7a49-969b-46ad-940c-c7de85499f4e.png)

**Note**: Might have to confirm with someone if whitespace is even allowed in the first place.

Have seen this issue present in both VSCode and IntelliJ

**Comment by evie-lau** [comment]
Update: whitespace is not supported in `server.env` files as per [IBM documentation](https://www.ibm.com/docs/en/was-liberty/base?topic=manually-customizing-liberty-environment)

`bootstrap.properties` is not explicit about it in its [documentation](https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-specifying-bootstrap-properties), but the examples in the page do show whitespace around the `=`

Thanks @cherylking for finding the documentation

**Comment by cherylking** [comment]
So for `server.env` we should probably detect the whitespace before/after the `=` and flag a diagnostic for it. For `bootstrap.properties`, we need to follow up and determine if it is supported or not. If whitespace is supported, then make our LS handle it accordingly.

**Comment by cherylking** [comment]
Followed up with Liberty developers and the `bootstrap.properties` file follows standard Java properties file conventions, which are summarized [here](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-) in the Java documentation.

After reading that, the main takeaway is that the whitespace directly before/after the `=` is ignored. There is a lot of special cases though with line continuation by using the escape `\`, and special quoting in the key to include a `=` or `:`.
