### ISSUE TITLE
Why I see message "Liberty Config Language Server requires Java 17 for functionality" in VS Code?

### ISSUE THREAD

**Issue by gasgithub** [OpenLiberty/liberty-language-server#156]
While running VS Code with latest Liberty Tools for Visual Studio Code installed, I'm seeing the following message:

```
The Liberty Config Language Server requires Java 17 for functionality. Please set 'xml.java.home' to point to Java 17 in VS Code settings or set the system JAVA_HOME environment variable to point to Java 17.
```

I'm not using Java 17 right now. 
How to configure Liberty Config LS to utilize Java 8 or 11?

I tried to set `xml.java.home` to point to Java 8 or 11 but it doesnt work.

Regards
Gas

**Comment by cherylking** [comment]
@gasgithub Java 17 is required for all of Liberty Tools. There were multiple dependencies that required it. So that meant Liberty Tools requires it. Please note that your projects can still configure and run with Java 8 or 11. It's just the IDE itself that must run with Java 17.

**Comment by cherylking** [comment]
@gasgithub By the way, thank you for raising this issue, as it has made us aware of our lack of documentation for this requirement. We are updating the various GH repo documents as a result for all the Liberty Tools components.
