### ISSUE TITLE
Error handling for liberty version setting

### ISSUE THREAD

**Issue by rzgry** [OpenLiberty/liberty-language-server#16]
Should have some kind of error handling if users input an invalid liberty version in the setting. Or for beta runtimes etc.

**Comment by yeekangc** [comment]
We won't need users to input unless they want to override, correct?  In what cases will users want to override?

**Comment by cherylking** [comment]
Not sure of the original intent of this issue, but the current design detects the installed version of Liberty (if it exists). Otherwise, the default schema and feature list (currently 22.0.0.6) are used. Closing this issue as I do not see the need for any error handling for this.
