### ISSUE TITLE
Validation error for `updateTrigger` attribute on the`applicationMonitor` element in server.xml

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/liberty-language-server#174]
This error was reported by Danny Haase in IBM Consulting. For the following element/attribute:

```
<applicationMonitor updateTrigger="${env.trigger}" />
```

This diagnostic was displayed:

![image](https://user-images.githubusercontent.com/29436451/234030253-02665a3d-d7f5-4a0f-b1fc-21e4dd649cc3.png)

The `updateTrigger` attribute is an enum. So it does not recognize a variable as being valid. Not sure if this should be addressed in the language server, or in the schema itself. It seems that some attributes (like `httpPort` on `httpEndpoint`) that expect a number have the following defined in the schema to allow for variables instead:

```
<xsd:simpleType name="intType">
        <xsd:union memberTypes="xsd:int variableType"/>
    </xsd:simpleType>
```

Can something similar be done for an enum attribute?

**Comment by cherylking** [comment]
If this cannot or should not be addressed in the schema itself, we would need to handle variable resolution. We already have an issue #18 open to add support for variable resolution. I imagine the language server would need to resolve all variables and maintain an in-memory copy of the server.xml with the actual values and pass that to the schema validator.

**Comment by scottkurz** [comment]
Investigating how LDT/WDT does this, it looks like they already maintain their own copy of the XSD:  https://raw.githubusercontent.com/OpenLiberty/open-liberty-tools/integration/dev/com.ibm.ws.st.core/server.xsd

**Comment by scottkurz** [comment]
Not sure if we NEED to use schemaVersion=1.1 to take advantage of the new outputVersion=2 construct (the use of the variableType with the enumerations). 

It'd probably be preferable to use 1.1 for the elements in which there's a difference
Though the 1.1 definition doesn't detect completely bogus elements it allows the known ones to be validated that they conform to the definition for those known types
