### ISSUE TITLE
Feature suggestion should maybe incorporate full feature element contents looking for version error

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-language-server#180]
Using the recent 1.0-SNAPSHOT, if I type `<feature>restConnector-1.0</feature>`and have the cursor after the '0', the feature suggestions seem to only include the "1.0" as context and completely ignores the "restConnector" part. 

![image](https://github.com/OpenLiberty/liberty-language-server/assets/4081634/ee36cf0a-aa43-4ea9-b110-c7ade477403a)

The correct feature is `restConnector-2.0`.

Should LCLS try to make a suggestion from the perspective of "right feature name but wrong version"??

**Comment by cherylking** [comment]
After changing the completion code to inspect what was passed in for the feature name, and only returning features that start with or contain the first part of the feature name (before the version number), the list displayed in Liberty Tools for Visual Studio Code still did not include useful entries. The IDEs themselves seem to have some logic that is doing the fuzzy matching.

I did take this opportunity though to prototype adding a quick fix for the diagnostic. Here are a couple of screenshots of what that would look like. I think this is a good work around and may even be better. What do you think @scottkurz ?

![Screenshot 2023-09-08 at 1 40 44 PM](https://github.com/OpenLiberty/liberty-language-server/assets/29436451/66cbeb49-bf1d-4bc9-9c70-462f009f9315)

![Screenshot 2023-09-08 at 1 40 33 PM](https://github.com/OpenLiberty/liberty-language-server/assets/29436451/9bc2ff16-6021-4352-97af-f8d3cbfdd9eb)

Here is a more interesting one where only part of the feature name was entered:

![Screenshot 2023-09-08 at 1 39 10 PM](https://github.com/OpenLiberty/liberty-language-server/assets/29436451/3437049f-5f35-4984-abc6-79cd3925eda2)

![Screenshot 2023-09-08 at 1 39 25 PM](https://github.com/OpenLiberty/liberty-language-server/assets/29436451/dccf223f-df9d-4b4e-81b5-7e406cdd4708)

**Comment by cherylking** [comment]
With the PRs that I merged, I am considering this fixed.
