### ISSUE TITLE
.libertyls and the related schema xsd fail to generate

### ISSUE THREAD

**Issue by dshimo** [OpenLiberty/liberty-language-server#184]
Between now and the December early release, LCLS seems to fail to extract the schema out of a running Liberty container. LCLS functionality is questionable with some seeing support and some not.

The process works past generating the container metadata and has a hiccup after. 
LibertyXSDURIResolver.java would be a good place to look.

**Comment by scottkurz** [comment]
I noticed this on Win 11.  Thinking it may be just a Windows issue...   the stack here:
> DockerService.generateServerSchemaXsdFromContainer(LibertyWorkspace) line: 100	
> LibertyXSDURIResolver.resolve(String, String, String) line: 84	

is building a command from a Windows Path:

```java
public static final Path DEFAULT_CONTAINER_SCHEMAGEN_JAR_PATH =
            DEFAULT_CONTAINER_WLP_DIR.resolve(Paths.get("bin", "tools", "ws-schemagen.jar"));
```

But it's a Linux container even though I"m running Windows.. so the Path is wrong.  We end up throwing an exception and returning `null` from **io.openliberty.tools.langserver.lemminx.LibertyXSDURIResolver.resolve(String, String, String)**

**Comment by cherylking** [comment]
@dshimo Were you on Windows when you recreated it?

**Comment by dshimo** [comment]
I could reproduce this on Mac.

**Comment by cherylking** [comment]
> I could reproduce this on Mac.

Ok, so the exception Scott saw is a different root cause than yours on Mac. Can you find out what exception is happening on Mac?

**Comment by cherylking** [comment]
@dshimo Any update on this? What exception is happening when running on mac?

**Comment by dshimo** [comment]
First, there seems to be multiple factors involved as there were varying results among the IDE's and OS's. And to clarify, my initial reproduction was on IntelliJ + Mac.

|   | VS Code | IntelliJ | Eclipse |
| --- | --- | --- | --- |
| Windows | `.libertyls` gets generated, but Docker returns with exit code 1. Results in using cached features | Not yet tested | Scott's result
| Mac | Works as intended | `.libertyls` does not get generated (1) | Struggling to get working, both with plugin dev and marketplace install (2)

(1) When trying to debug IntelliJ, the code doesn't seem to go through LibertyXSDUriResolver which contains our logic. It travels through LSPTextHover for hover information. This could be an entirely different behavior from Scott's Windows path issue.

(2) This result would've been good to have as a direct comparison to Scott's result, however I could not get XML support for server.xml nor devc to work in my Eclipse environment.
