### ISSUE TITLE
server.xml assist does not provide diagnostics for incorrect attributes

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-language-server#186]
### USE CASE
As one example, 

take the fact that we have different "context root" attribute names e.g. we have:
```xml
<webApplication contextRoot="ctx"
```
but
```xml
<web-ext context-root="ctx"..
```

It would be nice to have LCLS validate this and provide a diagnostic at least (not sure a quick fix is possible, but the user could do Ctrl+Space to get a completion suggestion to fix easily enough themselves).

### PROBLEM 

However, the Liberty XSD generated is something like:
```xml
    <xsd:complexType name="com.ibm.ws.app.manager.webappcfg"> 
        ...
        <xsd:anyAttribute processContents="skip"/>
```
preventing the XSD from detecting this as invalid.

### RUNTIME ISSUE LINK
This depends on https://github.com/OpenLiberty/open-liberty/issues/25579.   Presumably we'd address in the runtime and then see what if anything would be needed to pick up the change in LCLS.

**Comment by scottkurz** [comment]
Though we have achieved consensus in https://github.com/OpenLiberty/open-liberty/issues/25579 to make a change, creating a new v3 output version w/o the anyAttributes (except for special types like those for JDBC driver props), this still presents a challenge for older runtime drivers (ones before the future change).   

Is it possible it'd be better to have the LCLS do some "post-processing" on the XSD, which could thereby work for older runtimes as well? 

Note the flow for older runtimes could be something like:   upon git clone Liberty Tools validates against the stricter XSD (the LCLS default, which would presumably be the most updated one, at the v3 level), but after installing Liberty a runtime-specific schemaGen is performed (at the older v2 level).   Do we like this?

One other note:  after researching more, WDT/LDT actually detects unknown attributes using some custom XSD validation logic, e.g. rooted at: 
https://github.com/OpenLiberty/open-liberty-tools/tree/integration/dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/config
which dsiplays errors for attributes which are not known attributes, (in spite of the fact these are still XSD-valid, due to the anyAttribute).

**Comment by cherylking** [comment]
We will target the post-processing described above for the next feature release.

**Comment by cherylking** [comment]
I merged the xsd post processing in the `4q2023` branch.

**Comment by cherylking** [comment]
I am closing this issue since the post-processing of the cached and generated schema fixes this. Issue #203 is open to address using the published schemas once they are available.
