### ISSUE TITLE
Consider changes needed to handle new possibility of server config <include> elements pointing to a directory

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/liberty-language-server#204]
This OpenLiberty issue https://github.com/OpenLiberty/open-liberty/issues/25149 adds support for the <include> element location attribute to point to a directory containing server config files. This will affect any `lemminx-liberty` code that processes the server.xml `<include>` elements.

**Comment by cherylking** [comment]
The OL issue is currently targeted for 23.0.0.10 which has an eGA of 10/17. It is also planned to be included in the 23.0.0.10-beta which has an eGA of 9/19.

**Comment by evie-lau** [comment]
Checklist
- [ ] Diagnostics
  - [ ] Allow recognizing directories
  - [ ] Validate if directory exists for diagnostics
- [ ] Processing
  - [ ] Process directory direct children XML files alphabetically

**Comment by cherylking** [comment]
Should we also add the two way check that LMP/LGP is doing?

- [ ] If specify a directory, and it is a file issue a diagnostic.

- [ ] If specify a file, and it is a directory issue a diagnostic.
