### ISSUE TITLE
While testing 'Start in container' using podman, generating an empty .libertyls folder in Mac OS.

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-language-server#253]
OS: Mac
VS code: 1.84.2
Start in container using docker: everything working as expected.

While testing start in container using podman empty .libertyls folder is generating and server.xml is taking default cached 23.0.0.9.xsd file.

In server.xml, I am getting feature, loggging, keystore etc.. but list of features completion/hover info is not getting and diagnostics is not working after running start in container using podman. Tested with both gradle and maven project, in both I am seeing this same issue.

![image](https://github.com/OpenLiberty/liberty-tools-vscode/assets/114654953/05fe803d-fbbd-4dba-88c9-be4474e78744)

<img width="1422" alt="image" src="https://github.com/OpenLiberty/liberty-tools-vscode/assets/114654953/224057f8-8854-4eb0-ae9d-4b03275288e2">

![image](https://github.com/OpenLiberty/liberty-tools-vscode/assets/114654953/de1a7e1e-13ab-4469-992d-2955b8d72748)

**Comment by cherylking** [comment]
@mattbsox I decided to just go ahead and make the change in ci.common instead. Please see referenced PR above.

**Comment by cherylking** [comment]
@aparnamichael  The `3.10-SNAPSHOT` for the maven plugin (and `3.7.1-SNAPSHOT` for gradle) have been updated with a fix for this.

**Comment by aparnamichael** [comment]
I have tested with new snapshot and it is working fine for me.
![image](https://github.com/OpenLiberty/liberty-language-server/assets/114654953/d5a8a0f9-41c5-4652-b68a-0f1f5fab681b)
