### ISSUE TITLE
Use of guava com.google.common.io.Closeables isn't worth dragging in the entire dependency

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-language-server#254]
It adds footprint. more of a surface for the various scans....and it looks like just a wrapper with a bit of error handling around https://github.com/google/guava/blob/master/guava/src/com/google/common/io/Closeables.java which we are only using in one place (ParentProcessWatcher).  Looks like we could rewrite fairly easily.

**Comment by cherylking** [comment]
`guava` is pulled in by our dependencies...the only reason you see it in our pom.xml is to override the version (due to a CVE). So I don't think we can avoid having the `guava` dependency even if we stop using that particular class...just fyi.

**Comment by scottkurz** [comment]
> `guava` is pulled in by our dependencies...the only reason you see it in our pom.xml is to override the version (due to a CVE). So I don't think we can avoid having the `guava` dependency even if we stop using that particular class...just fyi.

Yeah, you're right.   Nevermind.
