### ISSUE TITLE
LibertyTextDocument puts a lot of info in the log

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-language-server#266]
As I edit my properties file in IntelliJ this language server prints the whole file to the log every time I make a change. This seems like too much output when there isn't an error. 

Could you remove this log statement and only print something if there is an error or a warning is needed?

LibertyTextDocument: `LOGGER.info(last.getText());`

**Comment by cherylking** [comment]
This seems like a mistake. It was probably for debugging and slipped in.

**Comment by turkeylurkey** [comment]
At first I thought it was my own debugging log!
