### ISSUE TITLE
Suggestions not available when the key is given partially first and deleted backwards 

### ISSUE THREAD

**Issue by JoshwinThomasIBM** [OpenLiberty/liberty-language-server#314]
We used to get suggestions for the property name  in server.env and bootstrap.properties file if we input key in parts for instance 
suggestions are displayed for something like " com.ibm.logg" even though the actual key starts as "com.ibm.ws.logg*" see the screen shot below 
<img width="920" alt="image" src="https://github.com/user-attachments/assets/c88b6a21-6af0-40d0-9c2d-8f88f244f773">
but once you select or click outside and try to get the suggestions again using ctl + space we don't get suggestions , see below 
<img width="629" alt="image" src="https://github.com/user-attachments/assets/2973ea51-9a5d-4476-93cc-4d1888a9de7e">

since moving forward with " com.ibm.logg " gave us suggestions, from a users perspective it was expected to get the suggestions on while removing backwards or when using ctl + space 

See the screen recording for the issue below 
 

https://github.com/user-attachments/assets/d97e8946-8f2c-4fbd-af00-424b8adca6c4

This behaviour is observed for all the 3 IDE's

**Comment by cherylking** [comment]
Matching on just `logg` is not provided by LCLS. This must be something the actual IDEs are doing. You see it is showing `logg` in a different color because that is all that it is matching on. Our code would only look for something that contains `com.ibm.logg` and there is nothing. Therefore you get no suggestions. We cannot provide a fix for this.

**Comment by cherylking** [comment]
I am going to close this issue since our completion code has never and should not match on the input String `com.ibm.logg`.  It is not a valid partial key. However, I would like to point out that if you just typed `logg`, I believe you would get some valid completions.
