### ISSUE TITLE
Displaying hover description for Invalid values in platform tag

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-language-server#327]
Displaying a hover description for an invalid value in the `platform` tag.

**Platform**

Windows OS
Liberty LemMinX Language Server 2.2

For example, `jakartaee-10.00` is an invalid value. I am receiving a diagnostic for this value, but at the same time, I am also receiving a description that includes the invalid value. Valid value is `jakartaee-10.0`

![394574673-9cc4b086-cbc6-41e8-b26b-a9e0c40008c9](https://github.com/user-attachments/assets/78dfccb1-1393-49af-8ec9-bc4568baed45)

**Comment by cherylking** [comment]
Thanks for bringing to our attention. We have a generic hover description for platform elements. We should add a check whether the platform is valid before providing a hover value.

**Comment by JoshwinThomasIBM** [comment]
Issue is resolved in LTV with LCLS - 2.2.1 - SNAPSHOT

**Comment by dessina-devasia** [comment]
Verified in LTI with LCLS 2.2.1-SNAPSHOT, and it is working as expected.
