### ISSUE TITLE
Tests fail under Java 8

### ISSUE THREAD

**Issue by datho7561** [OpenLiberty/liberty-language-server#36]
When running the tests with: `cd lemminx-liberty && ./mvnw clean compile verify`, they fail.

**Comment by kathrynkodama** [comment]
@datho7561 Can you provide more information on your java version?

**Comment by datho7561** [comment]
This is what I get from `java -version`:

openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

**Comment by datho7561** [comment]
Can't reproduce anymore.

**Comment by datho7561** [comment]
I can reproduce this again. Under Java 11 (OpenJDK 11.0.8) and Java 8 (OpenJDK 8.0.265), when I run `./mvnw clean verify`, some of the tests fail.

**Comment by rzgry** [comment]
Do you have any logs of the failures?

I tried w/ java 8 and java 11 on my machine and the tests passed. 

using: 
```
java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```
```
java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

**Comment by datho7561** [comment]
Logs for java 8 failure: https://pastebin.com/jYrJ1B54
Logs for java 11 failure: https://pastebin.com/TsaQizwb

**Comment by datho7561** [comment]
Sorry, I think I just installed a broken LemMinX build
