### ISSUE TITLE
Improve logic in determining a config file

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-language-server#40]
Currently the language server is activated for files named `server.xml`. 

A server.xml can point to other xml files using the `include` tag:
https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_setup_includes.html

We should improve the logic in how we determine which xml files to activate the language server on.

**Comment by cherylking** [comment]
This should also include any files located in pre-defined config dirs including:

`/usr/shared/config`
`/configDropins/override` under the server dir
`/configDropins/defaults` under the server dir
