### ISSUE TITLE
Investigate XML/LSP support in IntelliJ

### ISSUE THREAD

**Issue by rzgry** [OpenLiberty/liberty-language-server#41]
IntelliJ does not provide native LSP support need to investigate the options for using lsp in intellij.
* https://github.com/ballerina-platform/lsp4intellij
* https://github.com/redhat-developer/intellij-quarkus/tree/master/src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij

Also need to investigate how to extend XML support in IntelliJ since there is currently no LemMinX client for intellij.

**Comment by cherylking** [comment]
Liberty Tools for IntelliJ has handled the integration with LSP. Closing this issue.
