### ISSUE TITLE
[bootstrap.properties] Add list of valid values and default values

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/liberty-language-server#51]
For each common property we are recognizing, add a list of valid values and the default value if there are any. When completion is done on the property name, pre-populate the value with the default. If the value is changed, validate it against the pre-defined valid values.

Issue #50 needs to be done before this issue.

**Comment by cherylking** [comment]
https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-specifying-bootstrap-properties

The UFO slides did not seem to contain the following bootstrap.properties that are documented at the above doc link:

`default.http.port` and `default.https.port`

**Comment by evie-lau** [comment]
Completed default value preselect in #79 
Will finish diagnostic/validation using issue #75
