### ISSUE TITLE
[server.env] Add list of valid values and default values

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/liberty-language-server#52]
For each common env var we are recognizing, add a list of valid values and the default value if there are any. When completion is done on the env var name, pre-populate the value with the default. If the value is changed, validate it against the pre-defined valid values.

Issue https://github.com/OpenLiberty/liberty-language-server/issues/50 needs to be done before this issue.

**Comment by cherylking** [comment]
https://www.ibm.com/docs/en/was-liberty/base?topic=manually-customizing-liberty-environment

**Comment by evie-lau** [comment]
Completed default value preselect in #79 
Will finish diagnostic/validation using issue #75 to track
