### ISSUE TITLE
Diagnostic message for feature with trailing space is identical to msg for non-existent feature

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-language-server#64]
For a feature with trailing space like

```xml
    <featureManager>
        <feature>cdi-2.0 </feature>
```

I get a message that it doesn't exist:

> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/ydosppa/asi2/src/main/liberty/config/server.xml","diagnostics":[{"range":{"start":{"line":18,"character":17},"end":{"line":18,"character":25}},"severity":1,"source":"liberty-lemminx","message":"ERROR: The feature \"cdi-2.0 \" does not exist."}]}}

This is confusing since the runtime tolerates this by stripping the space, leaving me not realizing the extra space is the issue.   

Should the message be customized for this case?  Can it be downgraded in severity too (haven't really looked at the diagnostic part of the LSP in detail but I see the severity property in the payload).

**Comment by cherylking** [comment]
If the runtime tolerates this, I think we should strip the value before doing the diagnostic. Would also need to strip the value before getting the hover description.
