### ISSUE TITLE
Add diagnostic support for server.env and bootstrap.properties

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/liberty-language-server#75]
Add diagnostic/validation for properties in server.env and bootstrap.properties

For example:
- ~~invalid value (for those with well defined set of values)~~ - [Completed] #87
- invalid value for incorrect type (ie. integers, possibly within a certain range such as ports) such as `default.http.port` and `default.https.port`

**Comment by cherylking** [comment]
Here are the additional props/vars that I thought could be validated (most are an integer/whole number):

- [ ] WLP_DEBUG_ADDRESS (valid int)
- [ ] command.port (valid int)
- [ ] server.start.wait.time (valid int)
- [ ] osgi.console (valid int)
- [ ] org.osgi.framework.bootdelegation (comma separated list of packages)
- [ ] com.ibm.ws.logging.max.files (valid int)
- [ ] com.ibm.ws.logging.max.file.size (valid int)
- [ ] com.ibm.hpel.log.purgeMaxSize (valid int)
- [ ] com.ibm.hpel.log.purgeMinTime (valid int)
- [ ] com.ibm.hpel.log.fileSwitchTime (valid time of day)
- [ ] com.ibm.hpel.trace.purgeMaxSize (valid int)
- [ ] com.ibm.hpel.trace.purgeMinTime (valid int)
- [ ] com.ibm.hpel.trace.fileSwitchTime (valid time of day)

**Comment by cherylking** [comment]
Helpful Liberty doc with some of the min/max values for logging/trace: https://www.ibm.com/docs/en/was-liberty/base?topic=SSEQTP_liberty/com.ibm.websphere.liberty.autogen.nd.doc/ae/rwlp_config_logging.html
