### ISSUE TITLE
Fix text replacement for completion

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/liberty-language-server#78]
When revisiting a partially typed line, and invoking the completion choice, the selected property gets appended to the existing line instead of replacing the entire line.

ie: 

1. Type `com.ibm.`
2. Switch lines, bring cursor back to the end of `com.ibm.`
3. Type `ws.logging`, and select anything
4. Completion happens and ends up as `com.ibm.com.ibm.ws.logging...`

It looks like this can be modified by setting the TextEdit in the CompletionItem. `InsertReplaceEdit` can be used to specify the line and character positions for text insert and replace operations. The implementation may also depend on the Client Capabilities for the extension, which may vary per IDE extension. (ie. VSCode may support replace, but another IDE may not)

**Comment by arunvenmany-ibm** [comment]
This is working fine now in all supported IDE's
