### ISSUE TITLE
Enhance tests beyond basic functionality

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/liberty-language-server#89]
The language server features (hover, completion, diagnostics) for server.env and bootstrap.properties files need tests.

**Comment by cherylking** [comment]
Going to have David look into this since @evie-lau is still working on the diagnostics PR.

**Comment by evie-lau** [comment]
As of PR #108 and #112, all features (hover, completion, diagnostics) are tested.
Consider adding some tests for the Language Server itself, or for the TextDocumentService, where these tests try all the features at once. ie: check that completion works and has the property description, or hovering over the diagnostic gives the correct message.

**Comment by cherylking** [comment]
Closing this as the original request in the issue has been completed.
