### ISSUE TITLE
Set additional field values for liberty-ls CompletionItems

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-language-server#95]
For the CompletionItems contributed for the server.env values, I only see the label set:
```
CompletionItem [
  label = "WLP_LOGGING_JSON_FIELD_MAPPINGS"
  labelDetails = null
  kind = null
  tags = null
  detail = null
  documentation = null
  deprecated = null
  preselect = null
  sortText = null
  filterText = null
  insertText = null
  insertTextFormat = null
  insertTextMode = null
  textEdit = null
  textEditText = null
  additionalTextEdits = null
  commitCharacters = null
  command = null
  data = null
] 
```
Suggestion to set the `kind` value and the `labelDetails` value with a description of the field.
See a list of CompletionItemKind values here: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemKind

**Comment by cherylking** [comment]
@kathrynkodama I was just looking at the available options for `kind` and I think all of them would be `Text`. So I'm not sure how helpful that would be? As for the `labelDetails`, are you wanting the same description that already shows up for hover support for the var/property name? From reading the description, the label is the value that was selected. We would not have text specific for each value that can be selected for each var/prop.

**Comment by kathrynkodama** [comment]
@cherylking Thanks for considering. I agree that they would all be of kind `Text` so I suppose it would be okay to leave as-is. 

As for `labelDetails` - yes I was thinking the same description that shows up on hover though looking at the spec the `detail` or `documentation` attribute seems to fit better than `labelDetails`.  The `detail` attribute is defined as "A human-readable string with additional information about this item, like type or symbol information.". The `documentation` attribute is defined as "A human-readable string that represents a doc-comment". 
In VS Code it is helpful to click on the arrow next to a completion item for more information, see this example from the Language Server for MicroProfile:
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/26146482/191286174-50ca9dae-8da4-48f2-927a-2fcb28d3c1fb.png">

**Comment by cherylking** [comment]
@kathrynkodama Too bad they don't have more options for the `kind`, as we know some fields are integers, booleans etc. I'll look into adding the hover description to the `detail` field. At least the descriptions usually indicate what values are expected.

**Comment by evie-lau** [comment]
After comparing the changes, I don't agree that we should use `Text` for the kind. The default autocomplete (at least in VSCode) also includes text that appears in the document, and setting our completion items to `Text` makes them blend in with those, instead of standing out. 

Using the default kind `Property`: 
![image](https://user-images.githubusercontent.com/689163/193131344-04260502-7506-4813-b7ae-2f28fa810e6d.png)

Using the `Text` kind: 
![image](https://user-images.githubusercontent.com/689163/193131566-2c23f63c-772d-4230-bbd1-7abd892a2829.png)

This isn't as apparent in `server.env` because the property names are counted as whole words, but in `bootstrap.env`, the `.` separator allows VSCode to parse other words in the file and suggest them in the completion list.

**Comment by evie-lau** [comment]
I found something showing all the different kinds and their icons in VSCode: 
![image](https://user-images.githubusercontent.com/689163/193132907-e02d3bf7-3833-4245-a944-ca322effd2af.png)

**Comment by cherylking** [comment]
> I found something showing all the different kinds and their icons in VSCode: 

Yes, I already looked at that...and the only kind that makes sense is "Text". There is no String, Integer, Boolean etc.

**Comment by cherylking** [comment]
Decided we should set the kind to Property for the keys, and leave the values as Text.
